//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSP.Converter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Snippet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Snippet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGSP.Converter.Resources.Snippet", typeof(Snippet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivateGui.txt.
        /// </summary>
        internal static string ActivateGui {
            get {
                return ResourceManager.GetString("ActivateGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivateGuiConditioned.txt.
        /// </summary>
        internal static string ActivateGuiConditioned {
            get {
                return ResourceManager.GetString("ActivateGuiConditioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddSlideScene.txt.
        /// </summary>
        internal static string AddSlideScene {
            get {
                return ResourceManager.GetString("AddSlideScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.txt.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackgroundMusic.txt.
        /// </summary>
        internal static string BackgroundMusic {
            get {
                return ResourceManager.GetString("BackgroundMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackgroundMusicControl.txt.
        /// </summary>
        internal static string BackgroundMusicControl {
            get {
                return ResourceManager.GetString("BackgroundMusicControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackgroundMusicInit.txt.
        /// </summary>
        internal static string BackgroundMusicInit {
            get {
                return ResourceManager.GetString("BackgroundMusicInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraDefault.txt.
        /// </summary>
        internal static string CameraDefault {
            get {
                return ResourceManager.GetString("CameraDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base/Class.txt.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConversationSpeak.txt.
        /// </summary>
        internal static string ConversationSpeak {
            get {
                return ResourceManager.GetString("ConversationSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecuteEffect.txt.
        /// </summary>
        internal static string ExecuteEffect {
            get {
                return ResourceManager.GetString("ExecuteEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.txt.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExitToSlideScene.txt.
        /// </summary>
        internal static string ExitToSlideScene {
            get {
                return ResourceManager.GetString("ExitToSlideScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuiConversationOption.txt.
        /// </summary>
        internal static string GuiConversationOption {
            get {
                return ResourceManager.GetString("GuiConversationOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuiConversationSpeak.txt.
        /// </summary>
        internal static string GuiConversationSpeak {
            get {
                return ResourceManager.GetString("GuiConversationSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuiSpeakPlayer.txt.
        /// </summary>
        internal static string GuiSpeakPlayer {
            get {
                return ResourceManager.GetString("GuiSpeakPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If.txt.
        /// </summary>
        internal static string If {
            get {
                return ResourceManager.GetString("If", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsOver.txt.
        /// </summary>
        internal static string IsOver {
            get {
                return ResourceManager.GetString("IsOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base/Method.txt.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NextSlideScene.txt.
        /// </summary>
        internal static string NextSlideScene {
            get {
                return ResourceManager.GetString("NextSlideScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotifyDependingObjects.txt.
        /// </summary>
        internal static string NotifyDependingObjects {
            get {
                return ResourceManager.GetString("NotifyDependingObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectImage.txt.
        /// </summary>
        internal static string ObjectImage {
            get {
                return ResourceManager.GetString("ObjectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverExit.txt.
        /// </summary>
        internal static string OverExit {
            get {
                return ResourceManager.GetString("OverExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverObject.txt.
        /// </summary>
        internal static string OverObject {
            get {
                return ResourceManager.GetString("OverObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowGui.txt.
        /// </summary>
        internal static string ShowGui {
            get {
                return ResourceManager.GetString("ShowGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlideSceneActive.txt.
        /// </summary>
        internal static string SlideSceneActive {
            get {
                return ResourceManager.GetString("SlideSceneActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlideSceneStarted.txt.
        /// </summary>
        internal static string SlideSceneStarted {
            get {
                return ResourceManager.GetString("SlideSceneStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.txt.
        /// </summary>
        internal static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
    }
}
